# Generated by Django 3.0.3 on 2020-10-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dreamer', '0002_auto_20201013_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
