# Generated by Django 2.2.6 on 2020-11-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/uploads/setup')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
