# Generated by Django 2.2.6 on 2020-11-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0002_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='termscondition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
